In [1]:
import numpy as np

In [2]:
ar_1= np.array([1,2,3,4])
print(ar_1)

[1 2 3 4]


In [3]:
type(ar_1)

numpy.ndarray

In [4]:
ar_1.ndim

1

In [5]:
ar_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
ar_2.ndim

2

In [7]:
ar_1.size

4

In [8]:
ar_2.size

9

In [9]:
ar_2.shape

(3, 3)

In [10]:
ar_2.dtype

dtype('int32')

In [11]:
ar_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])