In [1]:
import numpy as np

In [5]:
mx_1s = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [7]:
mx_1s = np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


In [9]:
mx_1s.dtype

dtype('float64')

In [10]:
mx_2 = np.ones((3,4))
print(mx_2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
mx_3 = np.ones((4,5),dtype = int)
print(mx_3)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [14]:
mx_0s = np.zeros((4,4))
print(mx_0s)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
mx_0s = np.zeros((4,4),dtype = "bool")
print(mx_0s)

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


In [16]:
mx_0s = np.zeros((4,4),dtype=str)
print(mx_0s)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [19]:
e_str = ''
print(bool(e_str))

False


In [20]:
em_mx = np.empty((3,3))
print(em_mx)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 3.97228779e-321]
 [1.14587773e-312 2.11395428e-307 3.44900538e-307]]
