# numpy

In [1]:
import numpy as np


# Arange

In [2]:
#np.arange(1,13)
ar = np.arange(1,13)
print(ar)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
even = np.arange(1,15,2)
print(even)

[ 1  3  5  7  9 11 13]


# linspace

In [4]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

# Reshape

In [5]:
ar2 = ar.reshape(2,6)
print(ar2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ar3 = ar.reshape(2,3,2)
print(ar3)

In [6]:
ar_1= np.arange(1,13).reshape(2,6)
print(ar_1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# Ravel

In [7]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Flatten()

In [8]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Transpose

In [9]:
ar.transpose()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])