In [2]:
import numpy as np
import random 

In [3]:
np.random.random(1)

array([0.88126543])

In [4]:
np.random.random((3,3))

array([[0.42789646, 0.74077196, 0.30464652],
       [0.0715426 , 0.03682703, 0.05019037],
       [0.64149511, 0.4801064 , 0.48349166]])

In [10]:
np.random.randint(1,4)

3

In [11]:
np.random.randint(1,4,(4,4))

array([[2, 1, 1, 3],
       [3, 3, 2, 2],
       [2, 1, 3, 2],
       [2, 3, 1, 3]])

In [16]:
np.random.randint(1,4,(2,4,4))

array([[[3, 2, 3, 2],
        [1, 2, 1, 2],
        [3, 2, 3, 2],
        [1, 3, 2, 1]],

       [[1, 2, 2, 2],
        [2, 1, 1, 3],
        [1, 3, 1, 3],
        [2, 1, 1, 3]]])

In [17]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [18]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [19]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [20]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

In [22]:
np.random.randn(3,3)

array([[-1.58494101,  1.05535316, -1.92657911],
       [ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796]])

In [26]:
x =[1,2,3,4]
np.random.choice(x)

2

In [27]:
for i in range(20):
    print(np.random.choice(x))

1
4
1
1
3
1
3
3
1
4
2
1
4
2
3
3
2
3
3
4


In [32]:
np.random.permutation(x)

array([1, 3, 4, 2])