In [1]:
import numpy as np

In [3]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(1,10).reshape(3,3)
print(a1,"\n",a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
a1+a2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [5]:
np.add(a1, a2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [6]:
a1-a2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
np.subtract(a1,a2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [9]:
a1 / a2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.divide(a1,a2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
a1 * a2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [12]:
np.multiply(a1,a2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [13]:
a1 @ a2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [14]:
a1 .dot(a2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [15]:
a1.max()

9

In [16]:
a1.argmax()

8

In [18]:
a1.max(axis = 0)
# 0 = column
#1 = row

array([7, 8, 9])

In [20]:
a1.max(axis = 1)

array([3, 6, 9])

In [21]:
a1.min()

1

In [22]:
a1.argmin()

0

In [23]:
a1.min(axis = 0)

array([1, 2, 3])

In [24]:
a1.min(axis = 1)

array([1, 4, 7])

In [25]:
np.sum(a1 , axis = 0)

array([12, 15, 18])

In [27]:
np.sum(a1 , axis = 1)

array([ 6, 15, 24])

In [28]:
np.mean(a1)

5.0

In [29]:
np.sqrt(a1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [30]:
np.std(a1)

2.581988897471611

In [31]:
np.exp(a1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [32]:
np.log(a1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [33]:
np.log10(a1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])